### ISSUE TITLE
Sprint retrospective #5

### ISSUE THREAD

**Issue by ninaparipovic** [dartmouth-cs98/21f-visuol#198]
## Sprint #5 Retrospective:
* members in attendance:
  ![selfie proof of meeting](https://i.imgur.com/Zth3pLd.jpg)

  - [x] James
  - [x] Eddie
  - [x] Raymond
  - [x] Nina
  - [ ] Austin
* what worked well
  * We almost completed the offer comparison features
  * We allowed users to convert their hourly salaries to yearly
  * Allowed for recruiter accounts to be made
  * team bonding 
  * Almost finished with allowing users to share offers with others
* what didn't
  * Code review took some of our mental capacity away from focusing on the project
* self assessment on progress
  * where are you in relation to progress towards product and milestones?
    * give an estimate of how far towards your goals you are, do you think you're on track?
    Yes, we are on track to complete each weeks goals.
    * lay out *each* of the following weeks till end of term with brief goals for each
    * current week: In-app negotiation, Health care dictionary, cost of living
    * week 7: UI improvements and bug fixes
    * week 8: ad campaign
* briefly summarize any other topics/discussions

**Comment by timofei7** [comment]
don't forget screenshots. if you prefer and have screenshots already directly in PRs feel free to tag us in those.
