### ISSUE TITLE
Sprint Retrospective #6

### ISSUE THREAD

**Issue by eddie-ma-1** [dartmouth-cs98/21f-visuol#218]

**Comment by eddie-ma-1** [comment]
## Sprint #6 Retrospective:
* members in attendance:
  ![selfie proof of meeting](https://i.imgur.com/UXw7DP3.jpg)

  - [x] James
  - [x] Eddie
  - [x] Raymond
  - [x] Nina
  - [x] Austin
* what worked well
  * Feature to share offers with other users. 
  ![Shared Offers](https://i.imgur.com/CAbMWCA.png)
  * Fixed some bugs and UI/UX issues that have been persisting
      * State taxes
      * State selector instead of typing in state
  * Added some usability tooltips in the home menu
  * added different form input for recruiters 
  ![](https://i.imgur.com/H4Auo2i.png)

* what didn't
  * Some UI/UX things on the main feature end
      * Comparison still doesn't look quite right
  * Implementing some recent features has taken longer than expected. We're realizing that with each additional feature, there's more bug fixes and UI issues that we have to go back and fix. This has delayed us a little bit and we're thinking of what additional features to prioritize as the term comes to an end.
* self assessment on progress
  * current week: In-app negotiation, Health care dictionary, cost of living
    * week 8: UI improvements and bug fixes and ad campaign
* briefly summarize any other topics/discussions

**Comment by timofei7** [comment]
sounds like tech debt is catching up with you as you implement new features, definitely a problem that starts coming up as a project matures and grows.  whats sorts of things are you running up against - anything common among them?
