### ISSUE TITLE
Testing Plan and Results

### ISSUE THREAD

**Issue by jamesversch** [dartmouth-cs98/21f-visuol#219]
# Dogfooding/Testing
Outline each concept that you are testing with the user and craft questions to guide your user testing session. 

## Comparing offers:
1. Create an individual profile.
2. Create an offer.
__Q:  Is the input form intuitive? What should you change about it?__
__Q:  Do you think there's anything else about a job offer that would be important to visualize?__
3. Use the view offer feature.
__Q:  Are the compensation growth and savings graph features useful?__
__Q:  Are the sliders and various adjustments intuitive to use?__
__Q:  Anything else you'd like to see?__

5. Create a second offer.
6. Click on the compare offer tab and compare the two offers
__Q:  Is it intuitive how to pick companies to compare?__
__Q:  Are the comparison features useful?__
    * I.e. If you were trying to compare two offers, would you rather view then invdividually or use our side-by-side tool?

_repeat as needed_

# Bug Reports
_please list any bug reports and attach screenshots here_

**Comment by kevinlcaiug** [comment]
1
* Userflow seems intuitive and easy for anyone to use
2
* The input seems intuitive, perhaps adding some sort of degree of uncertainty to the bonus might be a useful feature
3
* Both features seem to give the user useful information regarding their potential future earnings
* Yes, we think that they allow users to play around with the application and see how something like savings rate can impact cumulative savings. The real-time update of the visualization completes the experience.
* Maybe a feature that would allow a user to compare more than 2 offers might be useful. It may also be valuable to give the user information about the benefits of having a larger salary vs stock options might be.
4
* Second offer feature is again intuitive. The UI could maybe make the division between two offers more obvious
5
* UI is intuitive. I'd like to see a feature that allows users to compare to some sort of industry-standard or mean for their seniority or job title
* The comparison feature is useful by showing the user two different visualizations. We think the axis on the graphs should either be the same scale or be overlayed. This would make the visual comparison more obvious to users
